# ============================================================================
# SKYNET - CONFIGURACIÓN PARA RENDER.COM
# ============================================================================
# Este archivo define la configuración del servicio web en Render
# ============================================================================

# Configuración del servicio
services:
  - type: web
    name: skynet-backend
    env: python
    plan: starter # o 'free' para plan gratuito
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    healthCheckPath: "/api/usuarios/validate-token/"

    # Variables de entorno (también se pueden configurar en el dashboard)
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true # Render generará una clave secreta automáticamente
      - key: ALLOWED_HOSTS
        value: "skynet-backend.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://tu-frontend.vercel.app,http://localhost:4200"
      - key: JWT_ACCESS_TOKEN_LIFETIME_HOURS
        value: "24"
      - key: JWT_REFRESH_TOKEN_LIFETIME_DAYS
        value: "7"
      - key: LOG_LEVEL
        value: "INFO"

    # Configuración de la base de datos (se vincula automáticamente)
    # DATABASE_URL se configura automáticamente cuando vinculas un servicio PostgreSQL

# Configuración de la base de datos PostgreSQL
databases:
  - name: skynet-postgres
    plan: starter # o 'free' para plan gratuito
    databaseName: skynet_db
    user: skynet_user
    # La contraseña se genera automáticamente

# Configuración adicional
region: oregon # o la región más cercana a tus usuarios
